# Please provide your answers as integers (don't use quotes)
# To find the row you want to add the value to, please refer
# to the delay table, and under "TOML Code", find the value
# stored. The value before the period should correspond to
# a value in between square brackets. For example, d1.a
# corresponds to the line below.

# For the first two tables, provide one integer, for the
# remaining tables, provide an array of 2 integers.

# For more info on TOML syntax, please refer to:
# https://toml.io/en/v1.0.0

[d1]
a = 10 # This is d1.a
b = 12
c = 14
d = 10

[d2]
a = 17
b = 19
c = 21
d = 24

# The first value corresponds to single-level
# The second value corresponds to two-level

[d3]
a = [10, 10]
b = [20, 12]
c = [30, 14]
d = [40, 10]
e = [21, 21]
f = [31, 31]
g = [41, 33]
h = [51, 35]

[d4]
a = [24, 24]
b = [34, 26]
c = [44, 28]
d = [54, 30]
e = [28, 28]
f = [45, 45]
g = [55, 47]
h = [65, 49]

[d5]
a = [22, 22]
b = [32, 32]
c = [42, 34]
d = [52, 36]

[d6]
a = [29, 29]
b = [46, 46]
c = [56, 48]
d = [66, 50]
